apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: multi-model-route
  namespace: default
spec:
  parentRefs:
    - name: ai-gateway
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - headers:
            - name: x-ai-eg-model
              type: Exact
              value: text-llm
      backendRefs:
        - name: self-hosted-text-llm
    - matches:
        - headers:
            - name: x-ai-eg-model
              type: Exact
              value: deepseek-r1-distill-llama-8b
      backendRefs:
        - name: deepseek-backend

