apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: multi-model-route
  namespace: default
spec:
  parentRefs:
    - name: ai-gateway
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - headers:
            - name: x-ai-eg-model
              type: Exact
              value: openai/gpt-oss-20b
      backendRefs:
        - name: gpt-oss
    - matches:
        - headers:
            - name: x-ai-eg-model
              type: Exact
              value: NousResearch/Llama-3.2-1B
      backendRefs:
        - name: llama