apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-neuron-device-plugin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: public.ecr.aws/neuron
    chart: neuron-helm-chart
    targetRevision: "1.3.0"
    helm:
      values: |
        scheduler:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
