apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: default
  sources:
  - chart: gateway-helm
    repoURL: docker.io/envoyproxy
    targetRevision: v1.5.3
    helm:
      valuesObject:
        config:
          envoyGateway:
            extensionApis:
              enableBackend: true
            provider:
              type: Kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
