apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: default
  source:
    chart: gateway-helm
    repoURL: docker.io/envoyproxy
    targetRevision: v1.5.3
    helm:
      values: |
        config:
          envoyGateway:
            extensionApis:
              enableBackend: true
            provider:
              type: Kubernetes
              kubernetes:
                rateLimitDeployment:
                  patch:
                    type: StrategicMerge
                    value:
                      spec:
                        template:
                          spec:
                            containers:
                              - imagePullPolicy: IfNotPresent
                                name: envoy-ratelimit
                                image: docker.io/envoyproxy/ratelimit:60d8081b
                # Add LoadBalancer service annotations for AWS
                envoyService:
                  patch:
                    type: StrategicMerge
                    value:
                      metadata:
                        annotations:
                          service.beta.kubernetes.io/aws-load-balancer-type: nlb
            rateLimit:
              backend:
                type: Redis
                redis:
                  url: redis.redis-system.svc.cluster.local:6379
            # Required: AI Gateway needs to fine-tune xDS resources generated by Envoy Gateway
            extensionManager:
              hooks:
                xdsTranslator:
                  translation:
                    listener:
                      includeAll: true
                    route:
                      includeAll: true
                    cluster:
                      includeAll: true
                    secret:
                      includeAll: true
                  post:
                    - Translation
                    - Cluster
                    - Route
                    - Secret
              service:
                fqdn:
                  hostname: ai-gateway-controller.envoy-ai-gateway-system.svc.cluster.local
                  port: 1063
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
