apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 19.6.4
    helm:
      parameters:
        - name: auth.enabled
          value: "false"
        - name: replica.replicaCount
          value: "0"
        - name: image.registry
          value: "public.ecr.aws"
        - name: image.repository
          value: "bitnami/redis"
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-ai-gateway-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/envoyproxy/ai-gateway
    path: manifests/charts/ai-gateway-crds-helm
    targetRevision: v0.4.0
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-ai-gateway-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-ai-gateway-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/envoyproxy/ai-gateway
    path: manifests/charts/ai-gateway-helm
    targetRevision: v0.4.0
    helm:
      values: |
        controller:
          args:
            - --extProcImage=docker.io/envoyproxy/ai-gateway-extproc:c87e367d026808e73dac690a4a353753c1d7d89c
            - --extProcImagePullPolicy=IfNotPresent
            - --extProcLogLevel=debug
            - --tlsCertDir=/certs
            - --tlsCertName=tls.crt
            - --tlsKeyName=tls.key
            - --enableLeaderElection=true
            - --rootPrefix=/
            - --cacheSyncTimeout=2m
            - --watchNamespaces=
            - --port=:1063
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-ai-gateway-system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: gateway-helm
    repoURL: docker.io/envoyproxy
    targetRevision: v1.5.3
    helm:
      values: |
        config:
          envoyGateway:
            extensionApis:
              enableBackend: true
            provider:
              type: Kubernetes
              kubernetes:
                rateLimitDeployment:
                  patch:
                    type: StrategicMerge
                    value:
                      spec:
                        template:
                          spec:
                            containers:
                              - imagePullPolicy: IfNotPresent
                                name: envoy-ratelimit
                                image: docker.io/envoyproxy/ratelimit:60d8081b
                # Add LoadBalancer service annotations for AWS
                envoyService:
                  patch:
                    type: StrategicMerge
                    value:
                      metadata:
                        annotations:
                          service.beta.kubernetes.io/aws-load-balancer-type: nlb
            rateLimit:
              backend:
                type: Redis
                redis:
                  url: redis.redis-system.svc.cluster.local:6379
            # Required: AI Gateway needs to fine-tune xDS resources generated by Envoy Gateway
            extensionManager:
              hooks:
                xdsTranslator:
                  translation:
                    listener:
                      includeAll: true
                    route:
                      includeAll: true
                    cluster:
                      includeAll: true
                    secret:
                      includeAll: true
                  post:
                    - Translation
                    - Cluster
                    - Route
                    - Secret
              service:
                fqdn:
                  hostname: ai-gateway-controller.envoy-ai-gateway-system.svc.cluster.local
                  port: 1063
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
