apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dynamo-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.ngc.nvidia.com/nvidia/ai-dynamo
    chart: dynamo-crds
    targetRevision: ${trimprefix(dynamo_version, "v")}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ServerSideApply=true
      - Replace=true
