model: fahadh4ilyas/Llama-4-Scout-17B-16E-Instruct-INT4
modelParameters:
  gpuMemoryUtilization: 0.8
  maxModelLen: 1024
  pipelineParallelSize: 1
  tensorParallelSize: 8

inference:
  serviceName: llama-4-scout-17b-vllm
  serviceNamespace: default
  accelerator: gpu
  framework: vllm
  modelServer:
    image:
      repository: vllm/vllm-openai
      tag: v0.10.2
    deployment:
      resources:
        gpu:
          requests:
            nvidia.com/gpu: 8
          limits:
            nvidia.com/gpu: 8
