apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: g5-gpu-karpenter
spec:
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 300s
    consolidationPolicy: WhenEmpty
  template:
    metadata:
      labels:
        amiFamily: ${ami_family}
        accelerator: nvidia
        gpuType: a10g
        instanceType: g5-gpu-karpenter
        type: karpenter
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: g5-gpu-karpenter
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - g5
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
            - 2xlarge
            - 4xlarge
            - 8xlarge
            - 12xlarge
            - 16xlarge
            - 24xlarge
            - 48xlarge
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
      taints:
        - effect: NoSchedule
          key: nvidia.com/gpu
          value: Exists
      terminationGracePeriod: 48h
  weight: 100
