apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: inferentia-inf2
spec:
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 300s
    consolidationPolicy: WhenEmpty
  template:
    metadata:
      labels:
        amiFamily: ${ami_family}
        accelerator: neuron
        instanceType: inferentia-inf2
        type: karpenter
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: g5-gpu-karpenter
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - inf2
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
      taints:
        - key: aws.amazon.com/neuron
          value: "true"
          effect: "NoSchedule"
      terminationGracePeriod: 48h
  weight: 100
