# AI Gateway Route for Bedrock integration using /anthropic/v1/messages endpoint
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: ai-gateway-route
  namespace: default
spec:
  parentRefs:
    - name: ai-gateway
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - headers:
            - name: x-ai-eg-model
              type: Exact
              value: anthropic.claude-3-haiku-20240307-v1:0
      backendRefs:
        - name: bedrock-aws
