# Pod Identity setup for AI Gateway with Bedrock
# Note: IAM Role and Pod Identity Association are created via Terraform (envoy-ai-gateway.tf)
# This file only creates the Kubernetes service account and RBAC

apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-gateway-dataplane-aws
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ai-gateway-dataplane-aws
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-gateway-dataplane-aws
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ai-gateway-dataplane-aws
subjects:
  - kind: ServiceAccount
    name: ai-gateway-dataplane-aws
    namespace: default
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: ai-gateway-with-aws
  namespace: default
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyServiceAccount:
        name: ai-gateway-dataplane-aws
