apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: neuron
spec:
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        amiFamily: ${ami_family}
        accelerator: neuron
    spec:
      expireAfter: 336h
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: neuron
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: eks.amazonaws.com/instance-family
          operator: In
          values:
            - inf2
            - trn1
            - trn2
      taints:
        - effect: NoSchedule
          key: aws.amazon.com/neuron
          value: Exists
      terminationGracePeriod: 24h0m0s
---
apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: neuron
spec:
  ephemeralStorage:
    iops: 3000
    size: 80Gi
    throughput: 125
  networkPolicy: DefaultAllow
  networkPolicyEventLogs: Disabled
  role: ${role}
  securityGroupSelectorTerms:
    - id: ${cluster_security_group_id}
  snatPolicy: Random
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${cluster_name}"
        Name: "${cluster_name}-private-secondary*" # Only secondary cidr subnets
